[package]
name = "flow-config"
version = "0.1.0"
edition = "2024"

[dependencies]
flow-core = { version = "0.1.0", path = "../flow-core" }
futures = "0.3.31"
tokio = { version = "1.45.0", features = ["fs"] }
