[package]
name = "flow"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bitflags = "2.9.0"
futures = "0.3.31"
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["rt", "macros", "rt-multi-thread"] }
x11rb-async = "0.13.1"
